apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vizual-x-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/infinity-x-one-system/vizual-x-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: VITE_API_URL
          value: https://api.vizual-x.com
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
